In [1]:
import numpy as np

In [6]:
T, H = 5, 4
hs = np.random.randn(T, H)  # Encoderが出力する隠れ層
a = np.array([0.8, 0.1, 0.03, 0.05, 0.02])  # 各単語の重み
ar = a.reshape(5, 1)

t = hs * ar
print(t)

[[ 2.94310593e-01  1.18617682e+00  1.88327663e-01  8.07870507e-02]
 [-1.59815105e-02  5.71821619e-02 -1.74376793e-01  1.78280836e-02]
 [ 8.57111544e-03  2.68956230e-02  3.81296966e-02  1.32300997e-02]
 [-3.19412337e-02 -4.10191553e-02  3.75452701e-02 -7.84594824e-04]
 [-3.67219665e-02  7.45298875e-03  2.29395744e-03  2.30546355e-02]]


In [7]:
np.sum(t, axis=0)

array([0.218237  , 1.23668844, 0.09191979, 0.13411527])

### batch process

In [8]:
N, T, H = 10, 5, 4
hs = np.random.randn(N, T, H)
a = np.random.randn(N, T)
ar = a.reshape(N, T, 1)

t = hs * ar
print(t.shape)

c = np.sum(t, axis=1)
print(c.shape)

(10, 5, 4)
(10, 4)


### Weight Sum

In [9]:
class WeightSum:
    """
    Context vector(c)を出力するclass
    context vectorは、各単語の重要度と各単語の隠れ層の積
    →context vectorには、重要度の高い単語の意味を多く持つことになる。
    """
    
    def __init__(self):
        self.params = []
        self.grads = []
        self.cache = None
    
    def forward(self, hs, a):
        N, T, H = hs.shape
        
        ar = a.reshape(N, T, 1)
        t = hs * ar
        c = np.sum(t, axis=1)
        
        self.cache= (hs, ar)
        return c
    
    def backword(self, dc):
        hs, ar = self.cache
        N, T, H =hs.shape
        dt = dc.reshape(N, 1, H)
        dar = dt * hs
        dhs = dt * ar
        da = np.sum(dar, axis=2)
        return dhs, da

### Attention Weight

In [ ]:
class AttentionWeight:
    def __init__(self):
        self.params = []
        self.grads = []
        self.softmax = Softmax()
        self.cache
    
    def forward(self, hs, h):
        N, T, H = hs.shape
        
        hr = h.reshape(N, 1, H)
        t = hs * hr
        s = np.sum(t, axis=2)
        a = self.softmax.forward(s)
        
        self.cache = (hs, hr)
        return a
    
    def backlward(self, da):
        hs, hr = self.cache
        N, T, H = hs.shape
        
        ds = self.softmax.backward(da)
        dt = ds.reshape(N, T, 1)
        dhs = dt * hr
        dhr = dt * hs
        dh = np.sum(dhr, axis=1)
        
        return dhs, dh